# Generated by Django 4.2.4 on 2024-08-20 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tagging', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedgerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_ledger_type', models.CharField(max_length=100, unique=True, verbose_name='Stock Ledger Type')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'stock_ledger_type',
                'verbose_name_plural': 'stock_ledger_types',
                'db_table': 'stock_ledger_type',
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(verbose_name='Entry Date')),
                ('pieces', models.IntegerField(default=0, verbose_name='Pieces')),
                ('gross_weight', models.FloatField(default=0.0, verbose_name='Gross Weight')),
                ('entry_type', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='tagging.entrytype', verbose_name='Entry Type')),
                ('stock_type', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='stock.stockledgertype', verbose_name='Stock type')),
                ('tag_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagging.taggeditems', verbose_name='Tag Details')),
            ],
            options={
                'verbose_name': 'stock_ledger',
                'verbose_name_plural': 'stock_ledger',
                'db_table': 'stock_ledger',
            },
        ),
    ]
