# Generated by Django 4.2.4 on 2024-08-31 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_estimationoldgold_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatedetails',
            name='round_off_amount',
            field=models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Round Off Amount'),
        ),
        migrations.AddField(
            model_name='estimationoldgold',
            name='gst_amount',
            field=models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='GST Amount'),
        ),
        migrations.CreateModel(
            name='EstimationChitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_account_number', models.CharField(max_length=150, verbose_name='Scheme Account Number')),
                ('scheme_weight', models.FloatField(default=0.0, verbose_name='Scheme Weight')),
                ('scheme_amount', models.FloatField(default=0.0, verbose_name='Scheme Amount')),
                ('bonus_amount', models.FloatField(default=0.0, verbose_name='Bonus Amount')),
                ('total_amount', models.FloatField(default=0.0, verbose_name='Total Amount')),
                ('estimation_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.estimatedetails', verbose_name='Estimation Details')),
            ],
            options={
                'verbose_name': 'estimation_chit_details',
                'verbose_name_plural': 'estimation_chit_details',
                'db_table': 'estimation_chit_details',
            },
        ),
    ]
