# Generated by Django 4.2.4 on 2024-08-31 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('billing', '0004_estimatedetails_round_off_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimationoldgold',
            name='dust_weight',
        ),
        migrations.RemoveField(
            model_name='estimationoldgold',
            name='metal_rate',
        ),
        migrations.RemoveField(
            model_name='estimationoldgold',
            name='old_metal_rate',
        ),
        migrations.RemoveField(
            model_name='estimationoldgold',
            name='purity',
        ),
        migrations.RemoveField(
            model_name='estimationoldgold',
            name='today_metal_rate',
        ),
        migrations.RemoveField(
            model_name='estimationoldgold',
            name='total_old_gold_value',
        ),
        migrations.AddField(
            model_name='estimationoldgold',
            name='old_amount',
            field=models.FloatField(default=0.0, verbose_name='Old Amount'),
        ),
        migrations.AddField(
            model_name='estimationoldgold',
            name='old_dust_weight',
            field=models.FloatField(default=0.0, verbose_name='Old Dust Weight'),
        ),
        migrations.AddField(
            model_name='estimationoldgold',
            name='old_rate',
            field=models.FloatField(default=0.0, verbose_name='Old Rate'),
        ),
        migrations.AddField(
            model_name='estimationoldgold',
            name='total_amount',
            field=models.FloatField(default=0.0, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='estimationoldgold',
            name='gst_amount',
            field=models.FloatField(default=0.0, verbose_name='GST Amount'),
        ),
        migrations.AlterField(
            model_name='estimationoldgold',
            name='old_gross_weight',
            field=models.FloatField(default=0.0, verbose_name='Old Gross Weight'),
        ),
        migrations.AlterField(
            model_name='estimationoldgold',
            name='old_metal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.metal', verbose_name='Metal'),
        ),
        migrations.AlterField(
            model_name='estimationoldgold',
            name='old_net_weight',
            field=models.FloatField(default=0.0, verbose_name='Old Net Weight'),
        ),
    ]
