# Generated by Django 4.2.4 on 2024-08-31 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_remove_estimationoldgold_dust_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimationtagitems',
            name='cover_weight',
        ),
        migrations.RemoveField(
            model_name='estimationtagitems',
            name='loop_weight',
        ),
        migrations.RemoveField(
            model_name='estimationtagitems',
            name='other_weight',
        ),
        migrations.RemoveField(
            model_name='estimationtagitems',
            name='tag_weight',
        ),
    ]
