# Generated by Django 4.2.4 on 2024-08-31 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_estimationtagitems_cover_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimationtagitems',
            old_name='tax_percent',
            new_name='gst_percent',
        ),
    ]
