# Generated by Django 4.2.4 on 2024-08-31 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_rename_tax_percent_estimationtagitems_gst_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimatedetails',
            name='diamond_amount',
        ),
        migrations.RemoveField(
            model_name='estimatedetails',
            name='stone_amount',
        ),
    ]
