# Generated by Django 4.2.4 on 2024-09-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_remove_estimatedetails_diamond_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimationtagitems',
            old_name='total_rate',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='estimationtagitems',
            old_name='without_gst_rate',
            new_name='with_gst_total_rate',
        ),
    ]
