# Generated by Django 4.2.4 on 2024-09-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_rename_total_rate_estimationtagitems_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='estimation_details',
            field=models.JSONField(default=list, null=True),
        ),
    ]
