# Generated by Django 4.2.4 on 2024-09-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_billingdetails_estimation_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdetails',
            name='estimation_details',
        ),
        migrations.AlterField(
            model_name='billingestimationdetails',
            name='estimation_details',
            field=models.JSONField(default=list, null=True),
        ),
    ]
