# Generated by Django 4.2.4 on 2024-09-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_remove_billingdetails_estimation_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingparticulardetails',
            name='gst_percent',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Gst Percent'),
        ),
    ]
