# Generated by Django 4.2.4 on 2024-09-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_rename_diamond_billingparticularsdiamonddetails_diamond_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingparticularsdiamonddetails',
            old_name='include_stone_weight',
            new_name='include_diamond_weight',
        ),
    ]
