# Generated by Django 4.2.4 on 2024-09-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_rename_include_stone_weight_billingparticularsdiamonddetails_include_diamond_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsalereturnitems',
            name='sale_return_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sale Return Type'),
        ),
        migrations.AddField(
            model_name='estimationsalereturnitems',
            name='sale_return_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sale Return Type'),
        ),
    ]
