# Generated by Django 4.2.4 on 2024-09-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_billingsalereturnitems_sale_return_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingsalereturnitems',
            name='sale_return_type',
        ),
        migrations.RemoveField(
            model_name='estimationsalereturnitems',
            name='sale_return_type',
        ),
        migrations.AddField(
            model_name='estimatedetails',
            name='sale_return_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sale Return Type'),
        ),
    ]
