# Generated by Django 4.2.4 on 2024-09-10 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_remove_billingsalereturnitems_sale_return_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='bill_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.billingtype', verbose_name='Bill Type'),
        ),
    ]
