# Generated by Django 4.2.4 on 2024-09-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_billingdetails_bill_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingparticulardetails',
            name='reduce_weight',
        ),
    ]
