# Generated by Django 4.2.4 on 2024-08-20 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMenthod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method_name', models.CharField(max_length=50, unique=True, verbose_name='Payment Method Name')),
                ('color', models.CharField(default=1, max_length=50, verbose_name='Color')),
                ('bg_color', models.CharField(default=1, max_length=50, verbose_name='BG Color')),
            ],
            options={
                'verbose_name': 'payment_method',
                'verbose_name_plural': 'payment_methods',
                'db_table': 'payment_method',
            },
        ),
        migrations.CreateModel(
            name='PaymentModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50, unique=True, verbose_name='Module Name')),
            ],
            options={
                'verbose_name': 'payment_module',
                'verbose_name_plural': 'payment_module',
                'db_table': 'payment_module',
            },
        ),
        migrations.CreateModel(
            name='PaymentProviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_provider_name', models.CharField(max_length=50, verbose_name='Payment Provider Name')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_management.paymentmenthod', verbose_name='Payment Method')),
            ],
            options={
                'verbose_name': 'payment_provider',
                'verbose_name_plural': 'payment_providers',
                'db_table': 'payment_provider',
            },
        ),
        migrations.CreateModel(
            name='CustomerPaymentTabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refference_number', models.CharField(max_length=100, verbose_name='Refference Number')),
                ('paid_amount', models.FloatField(default=0.0, verbose_name='Paid Amount')),
                ('payment_refference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Refference Number')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment Date')),
                ('customer_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer', verbose_name='Cutomer Details')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_management.paymentmenthod', verbose_name='Payment_method')),
                ('payment_module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_management.paymentmodule', verbose_name='Payment_module')),
                ('payment_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment_management.paymentproviders', verbose_name='Payment_provider')),
            ],
            options={
                'verbose_name': 'payment_table',
                'verbose_name_plural': 'payment_tables',
                'db_table': 'payment_table',
            },
        ),
        migrations.CreateModel(
            name='CommonPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refference_number', models.CharField(max_length=100, unique=True, verbose_name='Order Id')),
                ('total_amount', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Amount')),
                ('discount_percentage', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Discount Percentage')),
                ('discount_amount', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Discount Amount')),
                ('igst_percentage', models.FloatField(blank=True, default=0.0, null=True, verbose_name='IGST Percentage')),
                ('igst_amount', models.FloatField(blank=True, default=0.0, null=True, verbose_name='IGST Amount')),
                ('sgst_percentage', models.FloatField(blank=True, default=0.0, null=True, verbose_name='SGST Percentage')),
                ('sgst_amount', models.FloatField(blank=True, default=0.0, null=True, verbose_name='SGST Amount')),
                ('cgst_percentage', models.FloatField(blank=True, default=0.0, null=True, verbose_name='CGST')),
                ('cgst_amount', models.FloatField(blank=True, default=0.0, null=True, verbose_name='CGST')),
                ('others', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Others')),
                ('round_off_total', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Round Off')),
                ('hall_mark_charges', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Hall Mark Charges')),
                ('making_charge_per_gram', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Making Charge Per Gram')),
                ('flat_making_charge', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Flat Making Charge')),
                ('stone_amount', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Stone Amount')),
                ('diamond_amount', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Diamond Amount')),
                ('payable_amount', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Payable Amount')),
                ('salereturn_amount', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Salereturn Amount')),
                ('exchange_amount', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Exchange Amount')),
                ('advance_amount', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Advance Amount')),
                ('balance_amount', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Balance Amount')),
                ('amount_received', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Amount Received')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_payment_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('gst_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='masters.gsttype', verbose_name='GST Type')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_payment_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'common_payment',
                'verbose_name_plural': 'common_payments',
                'db_table': 'common_payment',
            },
        ),
    ]
