# Generated by Django 4.2.4 on 2024-08-20 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='Phone no')),
                ('door_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='Door no')),
                ('street_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Street name')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Area')),
                ('taluk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Taluk')),
                ('postal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Postal code')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='District')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('pincode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pincode')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='DOB')),
                ('aadhar_card', models.CharField(blank=True, max_length=500, null=True, verbose_name='Aadhar card')),
                ('pan_card', models.CharField(blank=True, max_length=500, null=True, verbose_name='Pan card')),
                ('gst_no', models.CharField(blank=True, max_length=500, null=True, verbose_name='GST No')),
                ('is_married', models.BooleanField(default=False, verbose_name='Status')),
                ('marriage_date', models.DateField(blank=True, null=True, verbose_name='Marriage Date')),
                ('upi_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='UPI ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at')),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='Modified by')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'customer_detail',
                'verbose_name_plural': 'customer_details',
                'db_table': 'customer_details',
            },
        ),
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(verbose_name='Entry Date')),
                ('invoice_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Invoice Number')),
                ('reffrence_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Refference Number')),
                ('transaction_amount', models.FloatField(default=0.0, verbose_name='Transaction Amount')),
                ('transaction_weight', models.FloatField(default=0.0, verbose_name='Transaction Weight')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Cancel Status')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.branch', verbose_name='Branch')),
                ('customer_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer', verbose_name='Customer Details')),
                ('entry_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='settings.salesentrytype', verbose_name='Entry Type')),
                ('transaction_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='settings.transactiontype', verbose_name='Transaction Type')),
            ],
            options={
                'verbose_name': 'customer_ledger',
                'verbose_name_plural': 'customer_ledger',
                'db_table': 'customer_ledger',
            },
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_group_name', models.CharField(max_length=100, unique=True, verbose_name='Customer Group')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at')),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='Modified by')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'customer_group',
                'verbose_name_plural': 'customer_groups',
                'db_table': 'customer_groups',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customergroup', verbose_name='Customer Group'),
        ),
    ]
