# Generated by Django 4.2.4 on 2024-08-20 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_name', models.CharField(max_length=50, unique=True, verbose_name='Calculation Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(max_length=50, null=True, verbose_name='Modified By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'calculation_type',
                'verbose_name_plural': 'calculation_types',
                'db_table': 'calculation_type',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_code', models.CharField(max_length=15, verbose_name='HSN Code')),
                ('item_id', models.CharField(max_length=10, unique=True, verbose_name='Item ID')),
                ('item_name', models.CharField(max_length=50, verbose_name='Item Name')),
                ('allow_zero_weight', models.BooleanField(default=False, verbose_name='Allow Zero Weight')),
                ('item_image', models.CharField(blank=True, max_length=250, null=True, verbose_name='Item Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('huid_rate', models.FloatField(default=0.0, max_length=50, verbose_name='HUID Rate')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(max_length=50, null=True, verbose_name='Modified By')),
                ('calculation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.calculationtype', verbose_name='Calculation Type')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('item_counter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='infrastructure.counter', verbose_name='Item Counter')),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.metal', verbose_name='Metal')),
                ('purity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.purity', verbose_name='Purity')),
            ],
            options={
                'verbose_name': 'item_detail',
                'verbose_name_plural': 'item_details',
                'db_table': 'item_detail',
            },
        ),
        migrations.CreateModel(
            name='ItemID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=10, unique=True, verbose_name='Item Id')),
            ],
            options={
                'verbose_name': 'item_id',
                'verbose_name_plural': 'item_ids',
                'db_table': 'item_id',
            },
        ),
        migrations.CreateModel(
            name='MeasurementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_name', models.CharField(max_length=50, unique=True, verbose_name='Measurement Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(max_length=50, null=True, verbose_name='Modified By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'measurement_type',
                'verbose_name_plural': 'measurement_types',
                'db_table': 'measurement_type',
            },
        ),
        migrations.CreateModel(
            name='StockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_type_name', models.CharField(max_length=25, unique=True, verbose_name='Stock Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(max_length=50, null=True, verbose_name='Modified By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'stock_type',
                'verbose_name_plural': 'stock_types',
                'db_table': 'stock_type',
            },
        ),
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_item_id', models.CharField(max_length=10, unique=True, verbose_name='Sub Item ID')),
                ('subitem_hsn_code', models.CharField(max_length=15, verbose_name='HSN Code')),
                ('sub_item_name', models.CharField(max_length=50, verbose_name='Sub Item Name')),
                ('allow_zero_weight', models.BooleanField(default=False, verbose_name='Allow Zero Weight')),
                ('sub_item_image', models.CharField(blank=True, max_length=250, null=True, verbose_name='Item Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(max_length=50, null=True, verbose_name='Modified By')),
                ('calculation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.calculationtype', verbose_name='Calculation Type')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('item_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.item', verbose_name='Item Details')),
                ('measurement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.measurementtype', verbose_name='Measurement Type')),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.metal', verbose_name='Metal')),
                ('purity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.purity', verbose_name='Purity')),
                ('stock_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.stocktype', verbose_name='Stock Type')),
                ('sub_item_counter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='infrastructure.counter', verbose_name='Item Counter')),
            ],
            options={
                'verbose_name': 'sub_item_detail',
                'verbose_name_plural': 'sub_item_details',
                'db_table': 'sub_item_detail',
            },
        ),
        migrations.CreateModel(
            name='SubItemID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_item_id', models.CharField(max_length=10, unique=True, verbose_name='Item Id')),
            ],
            options={
                'verbose_name': 'sub_item_id',
                'verbose_name_plural': 'sub_item_ids',
                'db_table': 'sub_item_id',
            },
        ),
        migrations.CreateModel(
            name='WeightType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_name', models.CharField(max_length=50, unique=True, verbose_name='Weight Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(max_length=50, null=True, verbose_name='Modified By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'weight_type',
                'verbose_name_plural': 'weight_types',
                'db_table': 'weight_type',
            },
        ),
        migrations.CreateModel(
            name='WeightCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wastage_percent', models.FloatField(max_length=25, verbose_name='item_Wastage Percentage')),
                ('flat_wastage', models.FloatField(max_length=25, verbose_name='Flat Wastage')),
                ('making_charge_gram', models.FloatField(max_length=25, verbose_name='Making Charge per Gram')),
                ('flat_making_charge', models.FloatField(max_length=25, verbose_name='Flat Making Charge')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(max_length=50, null=True, verbose_name='Modified By')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('item_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item', verbose_name='Item Details')),
                ('making_charge_calculation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='making_charge_calculation', to='product.weighttype', verbose_name='Making Charge Calculation')),
                ('wastage_calculation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_wastage_calculation', to='product.weighttype', verbose_name='Wastage Calculation')),
            ],
            options={
                'verbose_name': 'weight_calculation',
                'verbose_name_plural': 'weight_calculations',
                'db_table': 'weight_calculation',
            },
        ),
        migrations.CreateModel(
            name='SubItemWeightCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wastage_percent', models.FloatField(max_length=25, verbose_name='Wastage Percentage')),
                ('flat_wastage', models.FloatField(max_length=25, verbose_name='Flat Wastage')),
                ('making_charge_gram', models.FloatField(max_length=25, verbose_name='Making Charge per Gram')),
                ('flat_making_charge', models.FloatField(max_length=25, verbose_name='Flat Making Charge')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(max_length=50, null=True, verbose_name='Modified By')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('making_charge_calculation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subitem_making_charge_calculation', to='product.weighttype', verbose_name='Making Charge Calculation')),
                ('sub_item_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subitem', verbose_name='SubItem Details')),
                ('wastage_calculation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subitem_wastage_calculation', to='product.weighttype', verbose_name='Wastage Calculation')),
            ],
            options={
                'verbose_name': 'subitem_weight_calculation',
                'verbose_name_plural': 'subitem_weight_calculations',
                'db_table': 'subitem_weight_calculation',
            },
        ),
        migrations.CreateModel(
            name='SubItemPerPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_per_piece_rate', models.FloatField(default=0.0, verbose_name='Min Per Piece Rate')),
                ('per_piece_rate', models.FloatField(default=0.0, verbose_name='Per Piece Rate')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(max_length=50, null=True, verbose_name='Modified By')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('item_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subitem', verbose_name='SubItem Details')),
            ],
            options={
                'verbose_name': 'sub_per_piece',
                'verbose_name_plural': 'sub_per_piece',
                'db_table': 'sub_per_piece',
            },
        ),
        migrations.CreateModel(
            name='SubItemPerGramRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_gram_rate', models.FloatField(max_length=25, verbose_name='Per Gram Rate')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(max_length=50, null=True, verbose_name='Modified By')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('per_gram_weight_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.weighttype', verbose_name='Weight Type')),
                ('sub_item_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subitem', verbose_name='SubItem Details')),
            ],
            options={
                'verbose_name': 'sub_per_gram_rate',
                'verbose_name_plural': 'sub_per_gram_rates',
                'db_table': 'sub_per_gram_rate',
            },
        ),
        migrations.CreateModel(
            name='SubItemFixedRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_rate', models.FloatField(max_length=50, verbose_name='Fixed Rate')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(max_length=50, null=True, verbose_name='Modified By')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('sub_item_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subitem', verbose_name='SubItem Details')),
            ],
            options={
                'verbose_name': 'subitem_fixed_rate',
                'verbose_name_plural': 'subitem_fixed_rates',
                'db_table': 'subitem_fixed_rate',
            },
        ),
        migrations.CreateModel(
            name='RangeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_weight', models.FloatField(max_length=50, verbose_name='From Weight')),
                ('to_weight', models.FloatField(max_length=50, verbose_name='To Weight')),
                ('range_value', models.CharField(max_length=50, verbose_name='Range Values')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(max_length=50, null=True, verbose_name='Modified By')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'range_stock',
                'verbose_name_plural': 'range_stocks',
                'db_table': 'range_stock',
            },
        ),
        migrations.CreateModel(
            name='PerPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_per_piece_rate', models.FloatField(default=0.0, verbose_name='Min Per Piece Rate')),
                ('per_piece_rate', models.FloatField(default=0.0, verbose_name='Per Piece Rate')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(max_length=50, null=True, verbose_name='Modified By')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('item_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item', verbose_name='Item Details')),
            ],
            options={
                'verbose_name': 'per_piece',
                'verbose_name_plural': 'per_piece',
                'db_table': 'per_piece',
            },
        ),
        migrations.CreateModel(
            name='PerGramRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_gram_rate', models.FloatField(max_length=25, verbose_name='Per Gram Rate')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(max_length=50, null=True, verbose_name='Modified By')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('item_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item', verbose_name='Item Details')),
            ],
            options={
                'verbose_name': 'per_gram_rate',
                'verbose_name_plural': 'per_gram_rates',
                'db_table': 'per_gram_rate',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_name', models.CharField(max_length=50, unique=True, verbose_name='Measurement Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(max_length=50, null=True, verbose_name='Modified By')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'measurement_detail',
                'verbose_name_plural': 'measurement_details',
                'db_table': 'measurement_detail',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='stock_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.stocktype', verbose_name='Stock Type'),
        ),
        migrations.CreateModel(
            name='FixedRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_rate', models.FloatField(max_length=50, verbose_name='Fixed Rate')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(max_length=50, null=True, verbose_name='Modified By')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('item_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item', verbose_name='Item Details')),
            ],
            options={
                'verbose_name': 'fixed_rate',
                'verbose_name_plural': 'fixed_rates',
                'db_table': 'fixed_rate',
            },
        ),
    ]
