# Generated by Django 4.2.4 on 2024-08-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newpurchaseitemdetail',
            old_name='no_diamond_pieces',
            new_name='diamond_pieces',
        ),
        migrations.RenameField(
            model_name='newpurchaseitemdetail',
            old_name='hallmark',
            new_name='hallmark_charges',
        ),
        migrations.RenameField(
            model_name='newpurchaseitemdetail',
            old_name='others',
            new_name='other_charges',
        ),
        migrations.RenameField(
            model_name='newpurchaseitemdetail',
            old_name='no_stone_pieces',
            new_name='stone_pieces',
        ),
        migrations.RemoveField(
            model_name='newpurchase',
            name='hallmark',
        ),
        migrations.RemoveField(
            model_name='newpurchase',
            name='others',
        ),
        migrations.RemoveField(
            model_name='newpurchase',
            name='total_item',
        ),
        migrations.AddField(
            model_name='newpurchaseitemdetail',
            name='reduce_diamond_weight',
            field=models.BooleanField(default=False, verbose_name='Reduce Diamond Weight'),
        ),
        migrations.AddField(
            model_name='newpurchaseitemdetail',
            name='reduce_stone_weight',
            field=models.BooleanField(default=False, verbose_name='Reduce Stone Weight'),
        ),
    ]
