# Generated by Django 4.2.4 on 2024-08-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_rename_no_diamond_pieces_newpurchaseitemdetail_diamond_pieces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpurchase',
            name='is_canceled',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cancelled'),
        ),
    ]
