# Generated by Django 4.2.4 on 2024-08-20 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldGoldBillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_gold_bill_number', models.CharField(max_length=150, unique=True, verbose_name='Old Gold Bill Number')),
                ('old_gold_weight', models.FloatField(default=0.0, verbose_name='Old_gold_weight')),
                ('old_gold_pieces', models.IntegerField(default=0, verbose_name='Old Gold Pieces')),
                ('gst_percent', models.FloatField(default=0.0, verbose_name='Gst Percent')),
                ('total_gst_amount', models.FloatField(default=0.0, verbose_name='Total GST Pieces')),
                ('old_gold_amount', models.FloatField(default=0.0, verbose_name='Old Gold Amount')),
                ('is_billed', models.BooleanField(default=False, verbose_name='Billing Status')),
                ('refference_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Refference Number')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Status')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='Modified by')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('customer_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer', verbose_name='Customer')),
                ('gst_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='masters.gsttype', verbose_name='Gst Type')),
            ],
            options={
                'verbose_name': 'old_gold_bill_details',
                'verbose_name_plural': 'old_gold_bill_details',
                'db_table': 'old_gold_bill_details',
            },
        ),
        migrations.CreateModel(
            name='OldGoldItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_weight', models.FloatField(default=0.0, verbose_name='Old Weight')),
                ('old_rate', models.FloatField(default=0.0, verbose_name='Old Rate')),
                ('old_dust_weight', models.FloatField(default=0.0, verbose_name='Old Dust Weight')),
                ('old_net_weight', models.FloatField(default=0.0, verbose_name='Old Net Weight')),
                ('old_amount', models.FloatField(default=0.0, verbose_name='Old Amount')),
                ('gst_amount', models.FloatField(default=0.0, verbose_name='GST Amount')),
                ('total_amount', models.FloatField(default=0.0, verbose_name='Total Amount')),
                ('is_transffered', models.BooleanField(default=False, verbose_name='Transfer status')),
                ('old_bill_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='old_gold_management.oldgoldbilldetails', verbose_name='Old Bill Details')),
                ('old_metal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.metal', verbose_name='Metal')),
            ],
            options={
                'verbose_name': 'old_item_details',
                'verbose_name_plural': 'old_item_details',
                'db_table': 'old_item_details',
            },
        ),
    ]
