# Generated by Django 4.2.4 on 2024-08-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_gold_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldgolditemdetails',
            name='old_weight',
        ),
        migrations.AddField(
            model_name='oldgolditemdetails',
            name='old_gross_weight',
            field=models.FloatField(default=0.0, verbose_name='Old Gross Weight'),
        ),
        migrations.AddField(
            model_name='oldgolditemdetails',
            name='old_pure_weight',
            field=models.FloatField(default=0.0, verbose_name='Old Pure Weight'),
        ),
        migrations.AddField(
            model_name='oldgolditemdetails',
            name='old_reduce_weight',
            field=models.FloatField(default=0.0, verbose_name='Old Reduce Weight'),
        ),
        migrations.AddField(
            model_name='oldgolditemdetails',
            name='old_touch',
            field=models.FloatField(default=0.0, verbose_name='Old Touch'),
        ),
    ]
