# Generated by Django 4.2.4 on 2024-09-02 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('old_gold_management', '0002_remove_oldgolditemdetails_old_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldgolditemdetails',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.staff', verbose_name='Employee Id'),
        ),
    ]
