# Generated by Django 4.2.4 on 2024-09-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('old_gold_management', '0003_oldgolditemdetails_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldgolditemdetails',
            name='old_pure_weight',
        ),
    ]
