# Generated by Django 4.2.4 on 2024-08-28 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refinery_management', '0003_purificationissue_metal_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfercreationitems',
            name='refference_number',
        ),
    ]
