# Generated by Django 4.2.4 on 2024-08-28 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('refinery_management', '0004_remove_transfercreationitems_refference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='meltingissue',
            name='metal_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.metal', verbose_name='Metal Details'),
        ),
    ]
