# Generated by Django 4.2.4 on 2024-08-28 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('refinery_management', '0005_meltingissue_metal_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meltingrecipt',
            name='payment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='melting_payment_status', to='settings.paymentstatus', verbose_name='Payment Status'),
        ),
    ]
