# Generated by Django 4.2.4 on 2024-08-28 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('refinery_management', '0006_alter_meltingrecipt_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purificationrecipt',
            name='payment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_status', to='settings.paymentstatus', verbose_name='Payment Status'),
        ),
    ]
