# Generated by Django 4.2.4 on 2024-08-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinery_management', '0007_alter_purificationrecipt_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfercreation',
            name='is_issued',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
