# Generated by Django 4.2.4 on 2024-08-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinery_management', '0008_transfercreation_is_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='meltingissue',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Cancel status'),
        ),
        migrations.AddField(
            model_name='meltingissue',
            name='is_issued',
            field=models.BooleanField(default=False, verbose_name='Issue status'),
        ),
        migrations.AddField(
            model_name='meltingissue',
            name='is_received',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
