# Generated by Django 4.2.4 on 2024-08-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinery_management', '0009_meltingissue_is_cancelled_meltingissue_is_issued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meltingrecipt',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Cancel status'),
        ),
    ]
