# Generated by Django 4.2.4 on 2024-08-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinery_management', '0010_meltingrecipt_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='purificationissue',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Cancel status'),
        ),
        migrations.AddField(
            model_name='purificationissue',
            name='is_issued',
            field=models.BooleanField(default=False, verbose_name='Issue status'),
        ),
        migrations.AddField(
            model_name='purificationissue',
            name='is_received',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='purificationrecipt',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Cancel status'),
        ),
    ]
