# Generated by Django 4.2.4 on 2024-08-25 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_management', '0001_initial'),
        ('books', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=150, unique=True, verbose_name='Payment ID')),
                ('payment_date', models.DateTimeField(verbose_name='Payment Date')),
                ('payment_weight', models.FloatField(default=0.0, verbose_name='Payment Weight')),
                ('payment_amount', models.FloatField(default=0.0, verbose_name='Payment Amount')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Cancel Status')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('vendor_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.accountheaddetails', verbose_name='Vendor Details')),
            ],
            options={
                'verbose_name': 'vendor_payment',
                'verbose_name_plural': 'vendor_payment',
                'db_table': 'vendor_payment',
            },
        ),
        migrations.CreateModel(
            name='VendorWeightPaymentDenominations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_weight', models.FloatField(default=0.0, verbose_name='Metal Weight')),
                ('touch', models.FloatField(default=0.0, verbose_name='Touch')),
                ('pure_weight', models.FloatField(default=0.0, verbose_name='Pure Weight')),
                ('payment_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_management.vendorpayment', verbose_name='Payment Details')),
            ],
            options={
                'verbose_name': 'vendor_payment_weight_denominations',
                'verbose_name_plural': 'vendor_payment_weight_denominations',
                'db_table': 'vendor_payment_weight_denominations',
            },
        ),
        migrations.CreateModel(
            name='VendorLedgerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_ledger_type', models.CharField(max_length=100, unique=True, verbose_name='Vendor Ledger Type')),
                ('created_at', models.DateTimeField(verbose_name='Create Date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'vendor_ledger_type',
                'verbose_name_plural': 'vendor_ledger_types',
                'db_table': 'vendor_ledger_type',
            },
        ),
        migrations.CreateModel(
            name='VendorLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(verbose_name='Transaction Date')),
                ('refference_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Refference Number')),
                ('transaction_weight', models.FloatField(default=0.0, verbose_name='Transaction Weight')),
                ('transaction_amount', models.FloatField(default=0.0, verbose_name='Transaction Amount')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Cancel Status')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.branch', verbose_name='Branch')),
                ('transaction_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vendor_management.vendorledgertype', verbose_name='Transaction Type')),
                ('vendor_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.accountheaddetails', verbose_name='Vendor Details')),
            ],
            options={
                'verbose_name': 'vendor_ledger',
                'verbose_name_plural': 'vendor_ledger',
                'db_table': 'vendor_ledger',
            },
        ),
        migrations.CreateModel(
            name='VendorDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_id', models.CharField(max_length=150, unique=True, verbose_name='Discount ID')),
                ('discount_date', models.DateTimeField(verbose_name='Discount Date')),
                ('discount_weight', models.FloatField(default=0.0, verbose_name='Discount Weight')),
                ('discount_amount', models.FloatField(default=0.0, verbose_name='Discount Amount')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Cancel Status')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('vendor_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.accountheaddetails', verbose_name='Vendor Details')),
            ],
            options={
                'verbose_name': 'vendor_discount',
                'verbose_name_plural': 'vendor_discount',
                'db_table': 'vendor_discount',
            },
        ),
        migrations.CreateModel(
            name='VendorAmountPaymentDenominations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('payment_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_management.vendorpayment', verbose_name='Payment Details')),
                ('payment_method', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payment_management.paymentmenthod', verbose_name='Payment Methods')),
                ('payment_providers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment_management.paymentproviders', verbose_name='Payment Providers')),
            ],
            options={
                'verbose_name': 'vendor_payment_amount_denominations',
                'verbose_name_plural': 'vendor_payment_amount_denominations',
                'db_table': 'vendor_payment_amount_denominations',
            },
        ),
    ]
