# Generated by Django 4.2.4 on 2024-09-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemdetails',
            name='pieces',
            field=models.IntegerField(default=0, verbose_name='pieces'),
        ),
    ]
