# Generated by Django 4.2.4 on 2024-09-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_orderitemdetails_pieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemdetails',
            name='is_converted_to_lot',
            field=models.BooleanField(default=False, verbose_name='Convert to lot'),
        ),
    ]
