# Generated by Django 4.2.4 on 2024-08-20 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenuGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_menugroup_name', models.CharField(max_length=50, unique=True, verbose_name='Main Menu group name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at')),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='Modified by')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'main_menu_group',
                'verbose_name_plural': 'main_menu_groups',
                'db_table': 'main_menu_group',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50, unique=True, verbose_name='Menu name')),
                ('menu_path', models.CharField(max_length=50, unique=True, verbose_name='Menu path')),
                ('icon', models.FileField(blank=True, null=True, upload_to='menu_icon/', verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at')),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='Modified by')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
                'db_table': 'menus',
            },
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_name', models.CharField(max_length=50, verbose_name='Mode Name')),
                ('short_code', models.CharField(max_length=50, verbose_name='Payment Short Code ')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Payment Mode color')),
            ],
            options={
                'verbose_name': 'payment_mode',
                'verbose_name_plural': 'payment_mode',
                'db_table': 'payment_mode',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, verbose_name='Status Name')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Payment Status color')),
            ],
            options={
                'verbose_name': 'payment_status',
                'verbose_name_plural': 'payment_status',
                'db_table': 'payment_status',
            },
        ),
        migrations.CreateModel(
            name='StatusTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, verbose_name='Status Name')),
                ('module', models.CharField(max_length=50, verbose_name='Module')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='lot color')),
            ],
            options={
                'verbose_name': 'status_table',
                'verbose_name_plural': 'status_tables',
                'db_table': 'status_table',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=100, unique=True, verbose_name='Transaction Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'transaction_type',
                'verbose_name_plural': 'transaction_types',
                'db_table': 'transaction_type',
            },
        ),
        migrations.CreateModel(
            name='SalesEntryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type_name', models.CharField(max_length=100, unique=True, verbose_name='Entry Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'sale_entry_type',
                'verbose_name_plural': 'sales_entry_type',
                'db_table': 'sale_entry_type',
            },
        ),
        migrations.CreateModel(
            name='SaleReturnPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_days', models.IntegerField(verbose_name='Return Days')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_policy_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_policy_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'sale_return_policy',
                'verbose_name_plural': 'sale_return_policy',
                'db_table': 'sale_return_policy',
            },
        ),
        migrations.CreateModel(
            name='PrintModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation_is_a4', models.BooleanField(default=True, verbose_name='Estimation Is A4')),
                ('billing_is_a4', models.BooleanField(default=True, verbose_name='Billing Is A4')),
                ('billing_backup_is_a4', models.BooleanField(default=True, verbose_name='Billing Backup Is A4')),
                ('order_is_a4', models.BooleanField(default=True, verbose_name='Order Is A4')),
                ('repair_is_a4', models.BooleanField(default=True, verbose_name='Repair Is A4')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='print_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'print_module',
                'verbose_name_plural': 'print_modules',
                'db_table': 'print_module',
            },
        ),
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_permit', models.BooleanField(default=True, verbose_name='View')),
                ('add_permit', models.BooleanField(default=False, verbose_name='Add')),
                ('edit_permit', models.BooleanField(default=False, verbose_name='Edit')),
                ('delete_permit', models.BooleanField(default=False, verbose_name='Delete')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.menu', verbose_name='Menu')),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userrole', verbose_name='User role')),
            ],
            options={
                'verbose_name': 'menu_permission',
                'verbose_name_plural': 'menu_permissions',
                'db_table': 'menu_permissions',
            },
        ),
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_group_name', models.CharField(max_length=50, unique=True, verbose_name='Menu group name')),
                ('icon', models.FileField(blank=True, null=True, upload_to='menugroup_icon/', verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at')),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='Modified by')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('main_menu_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.mainmenugroup', verbose_name='Main Menu Group')),
            ],
            options={
                'verbose_name': 'menu_group',
                'verbose_name_plural': 'menu_groups',
                'db_table': 'menu_groups',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.menugroup', verbose_name='Menu Group'),
        ),
        migrations.CreateModel(
            name='IncentiveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incentive_typename', models.CharField(max_length=10, verbose_name='Incentive type name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active status')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incentive_typename_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='incentive_typename_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'incentive_types',
                'verbose_name_plural': 'incentive_types',
                'db_table': 'incentive_type',
            },
        ),
        migrations.CreateModel(
            name='IncentivePercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incentive_percent', models.FloatField(blank=True, null=True, verbose_name='Incentive percentage')),
                ('incentive_amount', models.FloatField(blank=True, null=True, verbose_name='Incentive amount')),
                ('from_amount', models.FloatField(verbose_name='Incentive from amount')),
                ('to_amount', models.FloatField(verbose_name='Incentive to amount')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active status')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incentive_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('incentive_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incentive_type', to='settings.incentivetype')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='incentive_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'incentive_percents',
                'verbose_name_plural': 'incentive_percents',
                'db_table': 'incentive_percent',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Gendor Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gender_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'settings_gender',
                'verbose_name_plural': 'settings_genders',
                'db_table': 'settings_gender',
            },
        ),
    ]
