# Generated by Django 4.2.4 on 2024-08-20 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_name', models.CharField(max_length=100, verbose_name='Counter name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(max_length=50, null=True, verbose_name='Modified By')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'counter',
                'verbose_name_plural': 'counters',
                'db_table': 'counters',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(max_length=100, verbose_name='Floor name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(max_length=50, null=True, verbose_name='Modified By')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'floor',
                'verbose_name_plural': 'floors',
                'db_table': 'floors',
            },
        ),
        migrations.CreateModel(
            name='CounterTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_from_date', models.DateField(blank=True, null=True, verbose_name='Target From Date')),
                ('target_to_date', models.DateField(blank=True, null=True, verbose_name='Target To Date')),
                ('target_pieces', models.IntegerField(default=0, verbose_name='Target Pieces')),
                ('target_weight', models.FloatField(default=0.0, max_length=50, verbose_name='Target Weight')),
                ('target_amount', models.FloatField(default=0.0, max_length=50, verbose_name='Target Amount')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.branch', verbose_name='Branch')),
                ('counter_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infrastructure.counter', verbose_name='Counter Details')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'counter_target',
                'verbose_name_plural': 'counter_targets',
                'db_table': 'counter_target',
            },
        ),
        migrations.AddField(
            model_name='counter',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infrastructure.floor', verbose_name='Floor'),
        ),
    ]
