# Generated by Django 4.2.4 on 2024-08-20 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueAdditionDesigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_fixed_rate', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Purchase Fixed Rate')),
                ('purchase_pergram_rate', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Purchase Per Gram Rate')),
                ('purchase_perpiece_rate', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Purchase Perpiece Rate')),
                ('purchase_touch', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Purchase Touch')),
                ('purchase_wastage_percent', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Purchase Wastage Percent')),
                ('purchase_flat_wastage', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Purchase Flat Wastage')),
                ('purchase_making_charge_gram', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Purchase Making Charge Gram')),
                ('purchase_flat_making_charge', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Purchase Flat Making Charge')),
                ('retail_touch', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='retail Touch')),
                ('retail_wastage_percent', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='retail Wastage Percent')),
                ('retail_flat_wastage', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='retail Flat Wastage')),
                ('retail_making_charge_gram', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='retail Making Charge Gram')),
                ('retail_flat_making_charge', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='retail Flat Making Charge')),
                ('vip_touch', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='vip Touch')),
                ('vip_wastage_percent', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='vip Wastage Percent')),
                ('vip_flat_wastage', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='vip Flat Wastage')),
                ('vip_making_charge_gram', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='vip Making Charge Gram')),
                ('vip_flat_making_charge', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='vip Flat Making Charge')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(max_length=50, null=True, verbose_name='Modified By')),
                ('calculation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.calculationtype', verbose_name='Calculation Type')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('designer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.accountheaddetails', verbose_name='Designer Name')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item', verbose_name='Item Details')),
                ('metal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.metal', verbose_name='Metal')),
                ('purchase_making_charge_calculation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='making_charge_calculation_type', to='product.weighttype', verbose_name='Purchase Making Charge Calculation Type')),
                ('purchase_pergram_weight_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pergram_weight_type', to='product.weighttype', verbose_name='Purchase Pergram Weight Type')),
                ('purchase_wastage_calculation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wastage_calculation_type', to='product.weighttype', verbose_name='Purchase Wastage Calculation Type')),
                ('sub_item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subitem', verbose_name='Sub Item Details')),
                ('tag_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.tagtypes', verbose_name='Tag Type')),
            ],
            options={
                'verbose_name': 'value_addition_designer',
                'verbose_name_plural': 'value_addition_designers',
                'db_table': 'value_addition_designer',
            },
        ),
        migrations.CreateModel(
            name='ValueAdditionCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_weight', models.FloatField(max_length=50, verbose_name='From Weight')),
                ('to_weight', models.FloatField(max_length=50, verbose_name='To Weight')),
                ('max_fixed_rate', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Fixed Rate')),
                ('max_wastage_percent', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Maximum Wastage Percent')),
                ('max_flat_wastage', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Maximum Flat Wastage')),
                ('max_making_charge_gram', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Maximum Making Charge Gram')),
                ('max_flat_making_charge', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Maximum Flat Making Charge')),
                ('max_per_gram_rate', models.FloatField(blank=True, default=0.0, max_length=50, null=True, verbose_name='Maximum Per Gram Rate')),
                ('min_per_piece_rate', models.FloatField(default=0.0, verbose_name='Min Per Piece Rate')),
                ('per_piece_rate', models.FloatField(default=0.0, verbose_name='Per Piece Rate')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(max_length=50, null=True, verbose_name='Modified By')),
                ('calculation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.calculationtype', verbose_name='Calculation Type')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('item_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.item', verbose_name='Item Details')),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.metal', verbose_name='Metal')),
                ('stock_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.stocktype', verbose_name='Stock Type')),
                ('sub_item_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.subitem', verbose_name='Sub Item Details')),
                ('tag_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.tagtypes', verbose_name='Tag Type')),
            ],
            options={
                'verbose_name': 'value_addition_customer',
                'verbose_name_plural': 'value_addition_customers',
                'db_table': 'value_addition_customer',
            },
        ),
        migrations.CreateModel(
            name='FlatWastageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True, verbose_name='Type Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(null=True, verbose_name='Modified at')),
                ('modified_by', models.CharField(max_length=50, null=True, verbose_name='Modified By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'flatwastage_type',
                'verbose_name_plural': 'flatwastage_type',
                'db_table': 'flatwastage_type',
            },
        ),
    ]
