# Generated by Django 4.2.4 on 2024-08-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('payment_management', '0001_initial'),
        ('masters', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspenseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspense_id', models.CharField(max_length=150, unique=True, verbose_name='Suspense ID')),
                ('is_redeemed', models.BooleanField(default=False, verbose_name='Redeem Status')),
                ('bill_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Bill Number')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Cancel Status')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='Created by')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.branch', verbose_name='Branch')),
                ('customer_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer', verbose_name='Customer Details')),
            ],
            options={
                'verbose_name': 'suspense_details',
                'verbose_name_plural': 'suspense_details',
                'db_table': 'suspense_details',
            },
        ),
        migrations.CreateModel(
            name='SuspensePaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=150, unique=True, verbose_name='Payment ID')),
                ('payment_date', models.DateTimeField(verbose_name='Payment Date')),
                ('created_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='Created by')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.branch', verbose_name='Branch')),
                ('suspense_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suspense_management.suspensedetails', verbose_name='Suspense Details')),
            ],
            options={
                'verbose_name': 'suspense_payment_details',
                'verbose_name_plural': 'suspense_payment_details',
                'db_table': 'suspense_payment_details',
            },
        ),
        migrations.CreateModel(
            name='SuspensePaymentDenominations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.FloatField(default=0.0, verbose_name='Paid Amount')),
                ('remark', models.CharField(blank=True, max_length=150, null=True, verbose_name='Remark')),
                ('payment_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suspense_management.suspensepaymentdetails', verbose_name='Suspense Payment Details')),
                ('payment_method', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payment_management.paymentmenthod', verbose_name='Payment Method')),
                ('payment_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment_management.paymentproviders', verbose_name='Payment Provider')),
            ],
            options={
                'verbose_name': 'suspense_payment_denominations',
                'verbose_name_plural': 'suspense_payment_denominations',
                'db_table': 'suspense_payment_denominations',
            },
        ),
        migrations.CreateModel(
            name='SuspenseItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_weight', models.FloatField(default=0.0, verbose_name='Metal Weight')),
                ('metal_amount', models.FloatField(default=0.0, verbose_name='Metal Amount')),
                ('total_amount', models.FloatField(default=0.0, verbose_name='Total Amount')),
                ('metal_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.metal', verbose_name='Metal Details')),
                ('suspense_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suspense_management.suspensedetails', verbose_name='Suspense Details')),
            ],
            options={
                'verbose_name': 'suspense_item_details',
                'verbose_name_plural': 'suspense_item_details',
                'db_table': 'suspense_item_details',
            },
        ),
    ]
