# Generated by Django 4.2.4 on 2024-09-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspense_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspensedetails',
            name='closed_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Closed By'),
        ),
        migrations.AddField(
            model_name='suspensedetails',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed Date'),
        ),
        migrations.AddField(
            model_name='suspensedetails',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Closed Status'),
        ),
    ]
